language: php
php:
  - '5.6'
  - '7.0'
before_script:
  - composer self-update
  - composer install --dev
script:
  - php vendor/bin/phpcs --report=xml --report-file=reports/phpcs.xml --standard=PSR2 --ignore=*/vendor/* -p -v ./
  - phpunit --bootstrap vendor/autoload.php tests

notifications:
    on_success: never
    on_failure: always
